#!/bin/bash
#. setup.sh
pushd ${OPENCV_OUT}
#echo "*********$@"

#cmake	-DBUILD_EXAMPLES:BOOL=ON -DBUILD_JASPER:BOOL=ON -DBUILD_JPEG:BOOL=ON \
#-DBUILD_PNG:BOOL=ON -DBUILD_OPENEXR:BOOL=ON -DBUILD_TIFF:BOOL=ON \
#-DBUILD_ZLIB:BOOL=ON -DBUILD_opencv_world:BOOL=ON -DWITH_OPENGL:BOOL=ON \
#-DWITH_OPENMP:BOOL=ON -DCMAKE_SKIP_INSTALL_RPATH:BOOL=OFF \
#-DCMAKE_SKIP_RPATH:BOOL=OFF -DBUILD_opencv_ocl:BOOL=OFF \
#-DBUILD_SHARED_LIBS:BOOL=OFF \

#copied from cmake-gui : tools->show my changes
cmake -DBUILD_EXAMPLES:BOOL="1" -DBUILD_OPENEXR:BOOL="1" -DBUILD_SHARED_LIBS:BOOL=${OPENCV_BUILD_SHARED_LIBS} \
-DBUILD_opencv_world:BOOL="1" -DBUILD_JASPER:BOOL="1" -DBUILD_ZLIB:BOOL="1" \
-DWITH_OPENCL:BOOL="0" -DWITH_OPENMP:BOOL="1" -DBUILD_TIFF:BOOL="1" -DBUILD_JPEG:BOOL="1" \
-DWITH_OPENGL:BOOL="1" -DBUILD_PNG:BOOL="1" \
${OPENCV_SRC}
time make $@
popd
